baseurl = "https://wilsoncai1992.github.io/"
languageCode = "en-us"
title = "Wilson Cai"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-89370962-1"

[params]
	# General information
	author = "wilsoncai1992"
	description = "Ph.D. in Statistics"
	copyright = "Wilson Cai"

	# Repository
	provider = ""
	repo_url = ""

	version = ""
	logo = ""
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "cyan"
    	accent  = "blue"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "wilsoncai1992"
	email   = "wcai@berkeley.edu"


[[menu.main]]
	name   = "About"
	url    = "about/"
	weight = 5


[[menu.main]]
	name   = "Experience"
	url    = "experience/"
	weight = 10

[[menu.main]]
	name   = "Research"
	url    = "research/"
	weight = 20

[[menu.main]]
	name   = "Teaching"
	url    = "teach/"
	weight = 30

[[menu.main]]
	name   = "Software"
	url    = "software/"
	weight = 40

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
